config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :asanas, only: :index
  resources :sequences, only: [:index, :create, :new] do
    resources :postures, only: [:index, :new]
  end
  resources :postures, only: :create
  get '/asanas/balancing', to: 'asanas#balancing'
  get '/asanas/inversion', to: 'asanas#inversion'
  get '/asanas/backbending', to: 'asanas#backbending'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/auth/:provider/callback', to: 'sessions#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asana.rb
class Asana < ApplicationRecord
    has_many :postures
    has_many :sequences, through: :postures
    scope :balancing, -> { where(category: 'Balancing') }
    scope :inversion, -> { where(category: 'Inversion') }
    scope :backbending, -> { where(effect_on_spine: 'Backbend') }


end

app/models/posture.rb
class Posture < ApplicationRecord
    belongs_to :asana
    belongs_to :sequence
    validates_presence_of :duration
end

app/models/sequence.rb
class Sequence < ApplicationRecord
    belongs_to :user
    has_many :postures
    has_many :asanas, through: :postures
    validates_presence_of :name

    def duration
        self.postures.sum do |posture|
            posture.duration
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :sequences
    validates_presence_of :username, :password
    validates_uniqueness_of :username
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        User.find_by(id: session[:user_id])
    end

    def require_login
        redirect_to asanas_path unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def log_in(user)
        session[:user_id] = user.id
    end

end

app/controllers/asanas_controller.rb
class AsanasController < ApplicationController

    def index
        @asanas = Asana.all
    end

    def balancing
        @asanas = Asana.balancing
        render :index
    end

    def inversion
        @asanas = Asana.inversion
        render :index
    end

    def backbending
        @asanas = Asana.backbending
        render :index
    end

end

app/controllers/postures_controller.rb
class PosturesController < ApplicationController
    before_action :require_login
    before_action :get_sequence, only: [:index, :new]

    def index
        redirect_if_request_invalid
    end

    def new
        redirect_if_request_invalid
        @posture = Posture.new
    end

    def create
        @sequence = Sequence.find_by(id: params[:posture][:sequence_id])
        if user_authorized?
            @posture = Posture.new(posture_params)
            if @posture.save
                redirect_to sequence_postures_path(@posture.sequence)
            else
                render :new
            end
        else
            redirect_to sequences_path
        end
    end

    private

    def get_sequence
        @sequence ||= Sequence.find_by(id: params[:sequence_id])
    end

    def user_authorized?
        @sequence.user && (@sequence.user.id == current_user.id)
    end

    def redirect_if_request_invalid
        if @sequence.nil? || !user_authorized?
            redirect_to sequences_path
        end
    end

    def posture_params
        params.require(:posture).permit(:asana_id, :duration, :variation, :sequence_id)
    end

end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
    before_action :require_login

    def index
        @sequences = current_user.sequences
    end

    def new
        @sequence = Sequence.new
    end

    def create
        @sequence = current_user.sequences.build(sequence_params)
        if @sequence.save
            redirect_to new_sequence_posture_path(@sequence)
        else
            render :new
        end
    end

    private

    def sequence_params
        params.require(:sequence).permit(:name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        # if a user logged in with omniauth (how can we tell?) 
        if request.env["omniauth.auth"]
            #then find or create them in the db by uid
            @user = User.find_by(github_uid: request.env["omniauth.auth"]["uid"])
            if @user.nil?
                @user = User.create(username: request.env["omniauth.auth"]["info"]["nickname"], github_uid: request.env["omniauth.auth"]["uid"], password: "github")
            end
            log_in(@user)
            redirect_to sequences_path
        else
            # locally authenticate the user - verify they exist in the db by username
            # and that their password matches what is in the db
            @user = User.find_by(username: params[:username])
            if !@user
                @error = "Account not found. Please try again."
                render :new
            elsif !@user.authenticate(params[:password])
                @error = "Password incorrect. Please try again."
                render :new
            else
                # if it does, "log them in" with the session hash
                # and redirect them to a meaningful place
                log_in(@user)
                redirect_to sequences_path
            # otherwise, re render the login form, displaying a meaningful error
            end
        end
    end

    def destroy
        session.clear
        redirect_to asanas_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to new_sequence_path
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sequences_helper.rb
module SequencesHelper
    # given a duration, this method should convert it from seconds to minutes and seconds
    def format_duration_to_minutes(duration)
        "#{duration / 60} minutes and #{duration % 60} seconds"
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

end

app/views/asanas/index.html.erb
<h2> Asanas </h2>
<%= link_to "All Asanas", asanas_path %> |
<%= link_to "Only Balancing Asanas", asanas_balancing_path %> |
<%= link_to "Only Inversions", asanas_inversion_path %> |
<%= link_to "Only Backbending Asanas", asanas_backbending_path %>

<% @asanas.each do |asana| %>
    <div class="asana-card">
        <div class="asana-title">
            <p><%= asana.name %></p>
        </div>
        <div class="asana-names">
            <p><%= asana.sanskrit %></p>
            <p><%= asana.english %></p>
        </div>
        <div class="asana-details">
            <p><%= asana.category %></p>
            <p><%= asana.effect_on_spine %></p>
        </div>
        <div class="img">
            <img src=<%=asana.img%>>
        </div>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="header">
    <div class="title">Asana Sequence Builder</div>
    <% if current_user %>
        <div class="username">
            <i>welcome, <%= current_user.username %></i>
        </div>
    <% end %>
    <div class="nav">
    <div><a href="/asanas">Asanas</a></div>
    <% if logged_in? %>
        <div><a href="/sequences">My Sequences</a></div>
        <div><a href="/logout">Log Out</a></div>
    <% else %>
        <div><a href="/signup">Sign Up</a></div>
        <div><a href="/login">Log In</a></div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsanaBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <navbar>
      <%= render 'layouts/navbar' %>
    </navbar>
    <main class="wrapper">
      <%= yield %>
    </main>
  </body>
</html>

app/views/postures/index.html.erb
<h2> Sequence <i><%= @sequence.name %></i> </h2>
<%= link_to "Add New Posture", new_sequence_posture_path(@sequence) %>

<div class="postures">
    <% @sequence.postures.each.with_index(1) do |posture, index| %>
        <div class="posture-card">
            <h3><%= index %>. <%= posture.asana.name %></h3>
            <p><%= posture.duration %> seconds</p>
            <p><%= posture.variation %></p>
            <img src=<%=posture.asana.img%>>
        </div>
    <% end %>
</div>

app/views/postures/new.html.erb
<h2> Add a new posture to the sequence <i><%= @sequence.name %></i> </h2>

<%= render partial: '/errors', locals: { record: @posture } %>

<%= form_for @posture do |f| %>
    <%= f.label :asana %>
    <div><%= f.collection_select :asana_id, Asana.all, :id, :name, prompt: true %></div>
    <%= f.label :Duration %>
    <div><%= f.number_field :duration %></div>
    <%= f.label :Variation %>
    <div><%= f.text_area :variation %></div>
    <%= f.hidden_field :sequence_id, value: @sequence.id %>
    <%= f.submit %>
<% end %>

app/views/sequences/index.html.erb
<h2> Sequences </h2>

<%= link_to "Create New Sequence", new_sequence_path %>

<% @sequences.each do |sequence| %>
    <h3><%= link_to sequence.name, sequence_postures_path(sequence) %></h3>
    <p><%= sequence.postures.count %> postures</p>
    <%= format_duration_to_minutes(sequence.duration) %>
<% end %>

app/views/sequences/new.html.erb
<h2> Build a New Sequence </h2>

<%= render partial: '/errors', locals: { record: @sequence } %>

<%= form_for @sequence do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit "Create and Add Postures" %>
<% end %>

app/views/users/new.html.erb
<h2> Create a user account </h2>

<%= render partial: '/errors', locals: { record: @user } %>

<%= form_for @user, url: signup_path do |f| %>
    <%= f.label :Username %>
    <div><%= f.text_field :username %></div>
    <%= f.label :Password %>
    <div><%= f.password_field :password %></div>
    <%= f.label :confirm_password %>
    <div><%= f.password_field :password_confirmation %>
    <%= f.submit %>
<% end %>